apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: catalogue-cpu-stress
  namespace: sock-shop
spec:
  mode: one
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "2m"